// Required for API consumers
export enum ProjectState {
  CREATED = 'CREATED',
  ANALYZING = 'ANALYZING',
  PLANNING = 'PLANNING',
  VALIDATING_PLAN = 'VALIDATING_PLAN',
  READY = 'READY',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  BLOCKED = 'BLOCKED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum PhaseState {
  PENDING = 'PENDING',
  READY = 'READY',
  RUNNING = 'RUNNING',
  VERIFYING = 'VERIFYING',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  RECOVERING = 'RECOVERING',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  BLOCKED = 'BLOCKED',
  SKIPPED = 'SKIPPED',
  CANCELLED = 'CANCELLED',
}

export enum TaskState {
  PENDING = 'PENDING',
  READY = 'READY',
  RUNNING = 'RUNNING',
  DONE = 'DONE',
  FAILED = 'FAILED',
  BLOCKED = 'BLOCKED',
  CANCELLED = 'CANCELLED',
}
